config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('account.urls')),
    path('', include('product.urls')),
    path('blogs/', include('article.urls')),
    path('dashboard/', include('userpanel.urls')),
    path('compare/', include('compare.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('orders/', include('order.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.HomeView.as_view(), name='index-page'),
    path('aboutus/', views.about_us, name='aboutUs-page'),
    path('contact-us/', views.ContactUs.as_view(), name='contact-page'),
    path('faq/', views.faq, name='faq-page'),

]

product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product-list-page'),
    path('products/categories/<cat>/', views.ProductListView.as_view(), name='product-by-categories-page'),
    path('products/brands/<brand>/', views.ProductListView.as_view(), name='product-by-brands-page'),
    path('products/<slug:slug>', views.product_detail, name='product-detail-page'),
    path('allcategories', views.AllCategories.as_view(), name='all-categories-page'),

]

product/models.py
from django.db import models
from django.utils.text import slugify
from account.models import User


class ProductCategory(models.Model):
    Parent = models.ForeignKey('ProductCategory', on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    url_title = models.CharField(max_length=200)
    is_active = models.BooleanField()

    class Meta:
        verbose_name_plural = 'ProductsCategories'

    def __str__(self):
        return self.title


class ProductBrand(models.Model):
    title = models.CharField(max_length=200)
    url_title = models.CharField(max_length=200)
    is_active = models.BooleanField()

    class Meta:
        verbose_name_plural = 'ProductsBrand'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=250)
    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, null=False)
    category = models.ManyToManyField(ProductCategory)
    image = models.ImageField(upload_to='product/')
    short_descriptions = models.CharField(max_length=500, null=True, db_index=True)
    price = models.BigIntegerField()
    description = models.TextField()
    slug = models.SlugField(unique=True, editable=False, db_index=True, max_length=200)
    is_new = models.BooleanField()
    is_active = models.BooleanField()
    Discounted = models.BooleanField(default=False)
    discount_percent = models.FloatField(default=0)

    def calculate_price(self):
        the_final_amount = self.price - (self.discount_percent * self.price)
        return int(the_final_amount)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Product, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title


class ProductVisit(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.product)

    class Meta:
        verbose_name_plural = 'ProductsVisits'

product/views.py
from django.db.models import Count
from django.http import HttpRequest
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from product.models import Product, ProductCategory, ProductBrand, ProductVisit
from sitesetting.models import Advertising


class ProductListView(ListView):
    model = Product
    template_name = 'product/product_list.html'
    context_object_name = 'products'
    paginate_by = 9

    def get_queryset(self):
        query = super().get_queryset()
        chosen_category = self.kwargs.get('cat')
        searched_product = self.request.GET.get('search')
        chosen_brand = self.kwargs.get('brand')
        if chosen_category is not None:
            Product.objects.filter(category__url_title__iexact=chosen_category)
            query = query.filter(category__url_title__iexact=chosen_category)
        if chosen_brand is not None:
            query = query.filter(brand__url_title=chosen_brand)

        if searched_product is not None:
            query = query.filter(title__icontains=searched_product)
        return query

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['adv_irancell'] = Advertising.objects.filter(position__iexact=Advertising.BannerPosition.product_list,
                                                             title='ایرانسل').first()
        context['adv_mci'] = Advertising.objects.filter(position__iexact=Advertising.BannerPosition.product_list,
                                                        title='همراه اول').first()
        return context


def product_detail(request: HttpRequest, slug):
    user = request.user.id
    chosen_product = Product.objects.filter(slug=slug).first()

    if user is not None:
        visit = ProductVisit(product_id=chosen_product.id, user_id=request.user.id)
        visit.save()
    else:
        visit = ProductVisit(product_id=chosen_product.id)
        visit.save()
    related_product = Product.objects.filter(brand=chosen_product.brand).exclude(pk=chosen_product.id)[:4]
    return render(request, 'product/product_details.html', context={
        'products': chosen_product,
        'related_product': related_product
    })


def product_categories(request: HttpRequest):
    all_categories = ProductCategory.objects.annotate(category_count=Count('url_title')).filter(Parent_id=None)
    return render(request, 'product/components/categories.html', context={
        'all_categories': all_categories
    })


def product_brands(request: HttpRequest):
    all_brands = ProductBrand.objects.annotate(brand_count=Count("product")).all()
    return render(request, 'product/components/brand.html', context={
        'all_brands': all_brands
    })


class AllCategories(TemplateView):
    template_name = 'product/all_categories.html'

    def get_context_data(self, **kwargs):
        context = super(AllCategories, self).get_context_data()
        context['main_categories'] = ProductCategory.objects.filter(Parent=None).all()
        return context

product/templates/product/all_categories.html
{% extends 'shared/base.html' %}
{% block title %}
    All Categories
{% endblock %}
{% block content %}
    <body class="page page-template-default">
        <div tabindex="-1" class="site-content" id="content">
                <div class="container">
                    <br>
                    <div class="content-area" id="primary">
                        <main class="site-main" id="main">
                            <article class="page type-page status-publish hentry">
                                <header class="entry-header">
                                    <h1 itemprop="name" class="entry-title">Store Directory</h1>
                                </header><!-- .entry-header -->
                                <div itemprop="mainContentOfPage" class="entry-content">
                                    <div class="electro-store-directory">
                                        <hr class="no-margin">
                                        <div class="widget woocommerce widget_product_categories">
                                            <ul>
                                                {% for maincat in main_categories %}
                                                    <li class="cat-ite cat-parent"><a href="{% url 'product-by-categories-page' maincat.url_title %}"><span class="child-indicator open"><i class="fa fa-angle-up"></i></span>{{ maincat.url_title }}</a>
                                                    <ul class="children" style="display: none;">
                                                        {% for sub_cat in maincat.productcategory_set.all %}
                                                            <li class="cat-item"><a href="{% url 'product-by-categories-page' sub_cat.url_title %}"><span class="no-child"></span><span class="no-child"></span>{{ sub_cat.url_title }}</a></li>
                                                        {% endfor %}
                                                    </ul>
                                                    </li>
                                                {% endfor %}

                                            </ul>

                                        </div>
                                    </div>
                                </div><!-- .entry-content -->
                            </article><!-- #post-## -->
                        </main><!-- #main -->
                    </div><!-- #primary -->
                </div><!-- .col-full -->
            </div>
    </body>
{% endblock %}

product/templates/product/product_list.html
{% extends 'shared/base.html' %}
{% load thumbnail %}
{% load tags %}
{% load render_partial %}
{% block title %}
Product List
{% endblock %}
{% block content %}
    <body class="right-sidebar" >
        <div id="content" class="site-content" tabindex="-1">
        <div class="container">
            <div id="primary" class="content-area">
                <main id="main" class="site-main"><br>
                    <header class="page-header">
                        <h1 class="page-title">Products</h1>
                    </header>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="grid" aria-expanded="true">
                            <ul class="products columns-3">
                                {% for product in products %}
                                    <li class="product">
                                    <div class="product-outer" style="height: 391px;">
                                        <div class="product-inner">
                                            <span class="loop-product-categories"><a href="" rel="tag">{{ product.brand.url_title }}</a></span>

                                                <h3>{{ product.title }}</h3>
                                                <div class="product-thumbnail">
                                                    <a href="{% url 'product-detail-page' product.slug %}">
                                                    {% thumbnail product.image '250x232' crop='center' as im %}
                                                        <img src="{{ im.url }}" alt="">
                                                    {% endthumbnail %}
                                                    </a>
                                                </div>

                                            <div class="price-add-to-cart">
                                                <span class="price">
                                                    <span class="electro-price">
                                                        <ins><span class="amount">{{ product.price | three_digits_show }} </span></ins>
                                                    </span>
                                                </span>
                                                <a rel="nofollow" href="" class="button add_to_cart_button">Add to cart</a>
                                            </div><!-- /.price-add-to-cart -->
                                            <div class="hover-area">
                                                <div class="action-buttons">
                                                    <a href="" rel="nofollow">Add wishlist</a>
                                                    <a href="#" class="add-to-compare-link">Compare</a>
                                                </div>
                                            </div>

                                        </div><!-- /.product-inner -->
                                    </div><!-- /.product-outer -->
                                </li>
                                {% endfor %}

                            </ul>
                        </div>

                    </div>
                    <div class="shop-control-bar-bottom">

                        <nav class="woocommerce-pagination">
                            <ul class="page-numbers">
                            {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-numbers">Previous</a></li>
                            {% endif %}
                            {% for pageNumber in paginator.page_range %}
                                <li {% if page_obj.number == pageNumber %} class="active">
                                <a href="?page={{ pageNumber }}">{{ pageNumber }}</a></li>
                            {% else %}
                                <li ><a href="?page={{ pageNumber }}">{{ pageNumber }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}" class="page-numbers">Next</a></li>
                            {% endif %}


                            </ul>
                        </nav>
                    </div>

                </main><!-- #main -->
            </div><!-- #primary -->
            <br><br>
            <div id="sidebar" class="sidebar" role="complementary">
                {% render_partial 'product.views.product_categories' %}
                <aside class="widget widget_electro_products_filter">
                    <h3 class="widget-title">Filters</h3>
                    {% render_partial 'product.views.product_brands' %}

                    <aside class="widget woocommerce widget_price_filter">
                        <h3 class="widget-title">Price</h3>
                        <form action="#">
                            <div class="price_slider_wrapper">
                                <div style="" class="price_slider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
                                    <div class="ui-slider-range ui-widget-header ui-corner-all" style="left: 0%; width: 100%;"></div>
                                    <span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"></span>
                                    <span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 100%;"></span>
                                </div>
                                <div class="price_slider_amount">
                                    <a href="#" class="button">Filter</a>
                                    <div style="" class="price_label">Price: <span class="from">$428</span> — <span class="to">$3485</span></div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        </form>
                    </aside>
                </aside>
                <aside class="widget widget_text">
                    <div class="textwidget">
                        <a target="_blank" href="{{ adv_mci.url_title }}">
                            <img  src="{{ adv_mci.banner.url }}" alt="Banner">
                        </a>
                    </div>
                </aside>
                <aside class="widget widget_text">
                    <div class="textwidget">
                        <a target="_blank" href="{{ adv_irancell.url_title }}">
                            <img height="270" width="428" src="{{ adv_irancell.banner.url }}" alt="Banner">
                        </a>
                    </div>
                </aside>
                <aside class="widget widget_products">
                    <h3 class="widget-title">Latest Products</h3>
                    <ul class="product_list_widget">
                        <li>
                            <a href="" title="Notebook Black Spire V Nitro  VN7-591G">
                                <img width="180" height="180" src="/static/images/product-category/1.jpg" class="wp-post-image" alt=""><span class="product-title">Notebook Black Spire V Nitro  VN7-591G</span>
                            </a>
                            <span class="electro-price"><ins><span class="amount">$1,999.00</span></ins> <del><span class="amount">$2,299.00</span></del></span>
                        </li>

                        <li>
                            <a href="" title="Tablet Thin EliteBook  Revolve 810 G6">
                                <img width="180" height="180" src="/static/images/product-category/2.jpg" class="wp-post-image" alt=""><span class="product-title">Tablet Thin EliteBook  Revolve 810 G6</span>
                            </a>
                            <span class="electro-price"><span class="amount">$1,300.00</span></span>
                        </li>

                        <li>
                            <a href="" title="Notebook Widescreen Z51-70  40K6013UPB">
                                <img width="180" height="180" src="/static/images/product-category/3.jpg" class="wp-post-image" alt=""><span class="product-title">Notebook Widescreen Z51-70  40K6013UPB</span>
                            </a>
                            <span class="electro-price"><span class="amount">$1,100.00</span></span>
                        </li>

                        <li>
                            <a href="" title="Notebook Purple G952VX-T7008T">
                                <img width="180" height="180" src="/static/images/product-category/4.jpg" class="wp-post-image" alt=""><span class="product-title">Notebook Purple G952VX-T7008T</span>
                            </a>
                            <span class="electro-price"><span class="amount">$2,780.00</span></span>
                        </li>
                    </ul>
                </aside>
            </div>

        </div><!-- .container -->
    </div>
    </body>
{% endblock %}